/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hoatd
 */
public class frmCuasoChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmCuasoChinh
     */
    public frmCuasoChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelChinh = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniQuanLyLopHoc = new javax.swing.JMenuItem();
        mniQuanLysinhvien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitThongTinHethong = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelChinh.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Hệ thống");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dangnhap.jpg"))); // NOI18N
        mniDangNhap.setText("Dang Nhap");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangNhap);

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        jMenu1.add(mniThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mniQuanLyLopHoc.setText("Quản lý lớp học");
        mniQuanLyLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyLopHocActionPerformed(evt);
            }
        });
        jMenu2.add(mniQuanLyLopHoc);

        mniQuanLysinhvien.setText("Quản lý Sinh Viên");
        mniQuanLysinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLysinhvienActionPerformed(evt);
            }
        });
        jMenu2.add(mniQuanLysinhvien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Hệ thống");

        mitThongTinHethong.setText("Thông tin hệ thống");
        jMenu3.add(mitThongTinHethong);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
        frmDangNhap dangnhap=new frmDangNhap();
        dangnhap.setVisible(true);
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniQuanLysinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLysinhvienActionPerformed
        // TODO add your handling code here:
          PanelChinh.removeAll();
        PanelSinhVien   QLLopHoc= new PanelSinhVien();
        PanelChinh.add(QLLopHoc);
        PanelChinh.repaint();
        PanelChinh.validate();
    }//GEN-LAST:event_mniQuanLysinhvienActionPerformed

    private void mniQuanLyLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyLopHocActionPerformed
        // TODO add your handling code here:
        PanelChinh.removeAll();
        PanelQuanLyLopHoc   QLLopHoc= new PanelQuanLyLopHoc();
        PanelChinh.add(QLLopHoc);
        PanelChinh.repaint();
        PanelChinh.validate();
    }//GEN-LAST:event_mniQuanLyLopHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuasoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuasoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuasoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuasoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuasoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelChinh;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitThongTinHethong;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniQuanLyLopHoc;
    private javax.swing.JMenuItem mniQuanLysinhvien;
    private javax.swing.JMenuItem mniThoat;
    // End of variables declaration//GEN-END:variables
}
