/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Demo01_ChuaBai_TinhTien;

import javax.swing.JOptionPane;

/**
 *
 * @author Tran Manh Truong
 */
public class FrmCollectMoney extends javax.swing.JFrame {

    /**
     * Creates new form FrmCollectMoney
     */
    public FrmCollectMoney() {
        initComponents();
    }
    //kiểm tra chuỗi s nhập vào có phải là số nguyên?
    public boolean isInteger(String s)
    {
        try
        {
            int n = Integer.parseInt(s);//Convert từ String sang int
            return true;//nếu thành công thì trả về true
        }
        catch(Exception e) //nếu một lệnh trong try mà có lỗi
        {
            return false;
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabTinhTien = new javax.swing.JTabbedPane();
        panelTienDien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtChisodau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtChisocuoi = new javax.swing.JTextField();
        btnTinhTiendien = new javax.swing.JButton();
        txtTiendien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelTienInternet = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSothang = new javax.swing.JTextField();
        btnTinhTienInternet = new javax.swing.JButton();
        txtTienInternet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Chỉ số đầu:");

        jLabel2.setText("Chỉ số cuối:");

        btnTinhTiendien.setText("TÍNH TIỀN ĐIỆN");
        btnTinhTiendien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTiendienActionPerformed(evt);
            }
        });

        jLabel3.setText("Thành tiền:");

        javax.swing.GroupLayout panelTienDienLayout = new javax.swing.GroupLayout(panelTienDien);
        panelTienDien.setLayout(panelTienDienLayout);
        panelTienDienLayout.setHorizontalGroup(
            panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienDienLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTinhTiendien, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(txtChisodau)
                    .addComponent(txtChisocuoi)
                    .addComponent(txtTiendien, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelTienDienLayout.setVerticalGroup(
            panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienDienLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChisodau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChisocuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnTinhTiendien)
                .addGap(43, 43, 43)
                .addGroup(panelTienDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTiendien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        tabTinhTien.addTab("TínhTiền điện", panelTienDien);

        jLabel4.setText("Số Tháng:");

        btnTinhTienInternet.setText("TÍNH TIỀN INTERNET");
        btnTinhTienInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienInternetActionPerformed(evt);
            }
        });

        jLabel5.setText("Thành tiền:");

        javax.swing.GroupLayout panelTienInternetLayout = new javax.swing.GroupLayout(panelTienInternet);
        panelTienInternet.setLayout(panelTienInternetLayout);
        panelTienInternetLayout.setHorizontalGroup(
            panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienInternetLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(66, 66, 66)
                .addGroup(panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSothang)
                    .addComponent(txtTienInternet)
                    .addComponent(btnTinhTienInternet, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelTienInternetLayout.setVerticalGroup(
            panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTienInternetLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSothang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnTinhTienInternet)
                .addGap(43, 43, 43)
                .addGroup(panelTienInternetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTienInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        tabTinhTien.addTab("Tín tiền Internet", panelTienInternet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTinhTien)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTinhTien)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTienInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienInternetActionPerformed
        // TODO add your handling code here:
        String thang = this.txtSothang.getText();
        if(thang.equals("") || isInteger(thang)==false)
        {
            JOptionPane.showMessageDialog(this, "Tháng phải là số nguyên");
            return;
        }
        int sothang = Integer.parseInt(thang);
        CollectMoneyInternet TienInternet = new CollectMoneyInternet(sothang);
        TienInternet.calculateMoney();
        this.txtTienInternet.setText(Double.toString(TienInternet.getThanhTien()));
    }//GEN-LAST:event_btnTinhTienInternetActionPerformed

    private void btnTinhTiendienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTiendienActionPerformed
        // TODO add your handling code here:
        String dau, cuoi;
        dau = this.txtChisodau.getText();
        cuoi = this.txtChisocuoi.getText();
        if(dau.equals("") || isInteger(dau)==false)
        {
            JOptionPane.showMessageDialog(this, "Chỉ số đầu phải là số nguyên");
            return;
        }
        if(cuoi.equals("") || isInteger(cuoi)==false)
        {
            JOptionPane.showMessageDialog(this, "Chỉ số cuối phải là số nguyên");
            return;
        }
        //chuyển chuỗi thành số đế tính tiền
        int chisodau = Integer.parseInt(dau);
        int chisocuoi = Integer.parseInt(cuoi);
        CollectMoneyElectric TienDien = new CollectMoneyElectric(chisodau, chisocuoi);
        TienDien.calculateMoney();
        //chuyển thành tiền từ dạng số double sang dạng String để hiển thị
        this.txtTiendien.setText(Double.toString(TienDien.getThanhTien()));
    }//GEN-LAST:event_btnTinhTiendienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCollectMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCollectMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhTienInternet;
    private javax.swing.JButton btnTinhTiendien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelTienDien;
    private javax.swing.JPanel panelTienInternet;
    private javax.swing.JTabbedPane tabTinhTien;
    private javax.swing.JTextField txtChisocuoi;
    private javax.swing.JTextField txtChisodau;
    private javax.swing.JTextField txtSothang;
    private javax.swing.JTextField txtTienInternet;
    private javax.swing.JTextField txtTiendien;
    // End of variables declaration//GEN-END:variables
}
